sources/mapler/map/urls.py
from django.conf.urls import patterns, url
from map import views


urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^overview/', views.overview),
    url(r'^manage-points/', views.managePoints),
    url(r'^submit-point/', views.submitPoint),
    url(r'^delete-point/(\d+)/$', views.deletePoint),
    url(r'^manage-groups/', views.manageGroups),
    #groups
    url(r'^submit-create-group-form/', views.createGroupFormSubmit),
    url(r'^delete-group/(\S+)/$', views.deleteGroup),
    url(r'^add-user-to-group/(\S+)/(\S+)/$', views.addUserToGroup),
    url(r'^remove-user-from-group/(\S+)/(\S+)/$', views.removeUserFromGroup),
)

sources/mapler/mapler/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mapler.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^map/', include('map.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^data/', include('data_access.urls')),
    url(r'^file/', include('file_manager.urls')),

    # Default app
    url(r'^$', include('map.urls'))

)

sources/mapler/map/models.py
# Create your models here.

from django.db import models
from django.contrib.auth.models import User, Group

class Point(models.Model):
    owner = models.ForeignKey(User)
    owningGroup = models.ForeignKey(Group)
    creation_date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=12, decimal_places=8)
    longitude = models.DecimalField(max_digits=12, decimal_places=8)

class GroupExtension(models.Model):
	group = models.OneToOneField(Group)
	owner = models.ForeignKey(User)
	description = models.CharField(max_length=200)
	creation_date = models.DateTimeField(auto_now_add=True)

class GroupJoinRequest(models.Model):
    initiator = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    creation_date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=200)
    active = models.BooleanField()

class Attachment(models.Model):
    owner = models.ForeignKey(User)
    point = models.ForeignKey(Point)
    creation_date = models.DateTimeField(auto_now_add=True)
    fileName = models.CharField(max_length=256)
    directory = models.CharField(max_length=256)

class FileUploadSession(models.Model):
    attachment = models.ForeignKey(Attachment)
    uploadIdentifier = models.CharField(max_length=256)
    uploadFinished = models.BooleanField(default=False)
    uploadedPercentage = models.IntegerField(default=0)

class UserLog(models.Model):
    user = models.ForeignKey(User)
    time_stamp = models.DateTimeField(auto_now_add=True)
    ip = models.CharField(max_length=256)
    comment = models.CharField(max_length=128)

sources/mapler/map/forms/AddGroupForm.py
from django import forms

class AddGroupForm(forms.Form):
	maplerId = forms.IntegerField(widget=forms.HiddenInput())
	name = forms.CharField(max_length=20)
	description = forms.CharField(max_length=200)

sources/mapler/map/forms/AddPointForm.py
from django import forms

class AddPointForm(forms.Form):
	maplerId = forms.IntegerField(widget=forms.HiddenInput())
	group = forms.ChoiceField(choices=[])
	description = forms.CharField(max_length=200)
	longitude = forms.FloatField()
	latitude = forms.FloatField()

sources/mapler/map/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader
from forms.AddPointForm import AddPointForm
from forms.AddGroupForm import AddGroupForm
from models import Point, GroupExtension, UserLog
from django.template import RequestContext
from django.template.loader import render_to_string
from django.contrib.auth.models import User, Group
import json

def getUserName(request):
	userName = None
	if request.user.is_authenticated():
		userName = request.user.username
	return userName

def overview(request):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	t = loader.get_template('map/overwiev.html')
	c = Context({
		'userName': userName,
		'previewPointHtmlData' : getPointPreviewHtml(),
		'pointAttachmentsHtmlData': getPointAttachmentsHtml(request),
		'viewName': 'Overwiev',
	})
	return HttpResponse(t.render(c))

def managePoints(request):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	t = loader.get_template('map/manage-points.html')
	c = Context({
		'userName': userName,
		'addingPointHtmlData' : getAddPointForm(request),
		'editingPointHtmlData': getEditPointForm(request),
		'pointAttachmentsHtmlData': getPointAttachmentsHtml(request),
		'viewName': 'Manage Points',
	})
	return HttpResponse(t.render(c))

def submitPoint(request):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	pointDesc = ""

	maplerId = int(request.POST['maplerId'])
	if maplerId == -1: # new point
		newPoint = Point(owner=request.user)
		updatePointAccordingToForm(request.POST, newPoint)
		pointDesc = newPoint.description
		newPoint.save()
	else:
		point = Point.objects.get(pk=maplerId)
		if point.owner.username == userName:
			updatePointAccordingToForm(request.POST, point)
			pointDesc = point.description
			point.save()

	logRecord = UserLog()
	logRecord.ip = str(get_client_ip(request))
	logRecord.user = request.user
	logRecord.comment="Pt submit: " + pointDesc
	logRecord.save()

	return HttpResponseRedirect("/map/manage-points/")

def deletePoint(request, pointId):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	point = Point.objects.get(pk=int(pointId))
	if (point.owner.username==userName) :
		point.delete()

	return HttpResponseRedirect("/map/manage-points/")

def manageGroups(request):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	t = loader.get_template('map/manage-groups.html')
	c = Context({
		'userName': userName,
		'createGroupFormData': getAddGroupForm(request),
		'viewName': 'Manage Groups',
	})
	return HttpResponse(t.render(c))

def index(request):
	userName = getUserName(request)
	if userName != None:
		return HttpResponseRedirect("/map/overview")

	t = loader.get_template('map/index.html')
	c = Context({
		# 'userName': userName,
	})
	return HttpResponse(t.render(c))

def updatePointAccordingToForm(form, point):
	group = Group.objects.get(name=form['group'])

	point.description = form['description']
	point.latitude = form['latitude']
	point.longitude = form['longitude']
	# temporary fix
	point.owningGroup = group

def getAddPointForm(request):
	addForm = AddPointForm(initial={'maplerId': -1})
	c = Context({
		'mode': 'add',
		'form': addForm,
		})
	rendered = render_to_string('map/point-edit.html', c, context_instance=RequestContext(request))
	return rendered

def getEditPointForm(request):
	editForm = AddPointForm(initial={'maplerId': -1})
	c = Context({
		'mode': 'edit',
		'form': editForm,
		})
	rendered = render_to_string('map/point-edit.html', c, context_instance=RequestContext(request))
	return rendered

def getPointPreviewHtml():
	c = Context({
		#'mode': 'edit',
		})
	rendered = render_to_string('map/point-view.html', c)
	return rendered

def getAddGroupForm(request):
	addForm = AddGroupForm(initial={'maplerId': -1})
	c = Context({
		# 'mode': 'add',
		'form': addForm,
		})
	rendered = render_to_string('map/group-edit.html', c, context_instance=RequestContext(request))
	return rendered

def getPointAttachmentsHtml(request):
	c = Context({ })
	rendered = render_to_string('map/pointAttachments.html', c, context_instance=RequestContext(request))
	return rendered

def createGroupFormSubmit(request):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	if request.method != 'POST':
		return HttpResponse(json.dumps({'success': False, 'errorMessage': 'Please use POST method to submit a form'}), content_type="application/json")

	# form = AddGroupForm(request.POST)
	# valid = form.is_valid()
	# groupName = form.cleaned_data['name']
	groupName = request.POST['name']
	groupName = groupName.replace(' ','_')
	description = request.POST['description']

	if groupName == '':
		return HttpResponse(json.dumps({'success': False, 'errorMessage': 'Group name could not be empty'}), content_type="application/json")

	uniqueName = True
	for (i, existedGroup) in enumerate(Group.objects.all()):
		if existedGroup.name.lower() == groupName.lower():
			uniqueName = False

	if not uniqueName:
		return HttpResponse(json.dumps({'success': False, 'errorMessage': 'Group with specified name already exists'}), content_type="application/json")

	newGroup = Group(name=groupName)
	newGroup.save()
	newGroup.user_set.add(request.user)
	newGroup.save()
	groupNameExt = GroupExtension(group=newGroup, description=description, owner=request.user)
	groupNameExt.save()

	return HttpResponse(json.dumps({'success': True}), content_type="application/json")

def deleteGroup(request, groupName):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	group = Group.objects.get(name=groupName)
	groupExt = GroupExtension.objects.get(group=group)
	points = Point.objects.filter(owningGroup=group)
	for (i, point) in enumerate(points):
		point.delete()
	groupExt.delete()
	group.delete()

	return HttpResponseRedirect("/map/manage-groups/")

def addUserToGroup(request, userName, groupName):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	group = Group.objects.get(name=groupName)
	user = User.objects.get(username=userName)
	group.user_set.add(user)
	group.save()

	return HttpResponseRedirect("/map/manage-groups/")

def removeUserFromGroup(request, userName, groupName):
	userName = getUserName(request)
	if userName == None:
		return HttpResponseRedirect("/")

	group = Group.objects.get(name=groupName)
	user = User.objects.get(username=userName)
	group.user_set.remove(user)
	group.save()

	return HttpResponseRedirect("/map/manage-groups/")

def get_client_ip(request):
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[0]
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip

sources/mapler/templates/map/group-edit.html
<div class="groupForm">
	<b><p id="groupFormMessage"></p></b>
	<form id="createGroupForm" action="/map/submit-create-group-form/">{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Create" />
	</form>

	<script type="text/javascript">

	var createGroupForm = {
		_createdCB: null,

		groupCreatedCallback: function(callback){
			_createdCB = callback;
		},

		_onGroupCreated: function(){
			_createdCB();
		}
	}

	$("#createGroupForm").submit(function( event ) {
		event.preventDefault();

		var url = $("#createGroupForm").attr('action');

	    $.ajax({
	           type: "POST",
	           url: url,
	           data: $("#createGroupForm").serialize(), // serializes the form's elements.
	           success: function(data)
	           {
	           		if (data.success) {
				    	$('#groupFormMessage').html("Successfully created");
				    	createGroupForm._onGroupCreated();
					} else {
						$("#createGroupForm").find('#id_name').val('');
					    $('#groupFormMessage').html(data.errorMessage);
					}
	           }
	    });
	});
	</script>

</div>

sources/mapler/templates/map/index.html
{% extends "map/master.html" %}

{% block master-child %}

<div id="main-wrapper" class="col-md-7">
	<h3>Wellcome to Mapler!</h3>
	<p>Please login or sign up.</p>
	<h4>Join groups to enjoy sharing</h4>
</div>

{% endblock master-child %}

sources/mapler/templates/map/manage-groups.html
{% extends "map/views-manager.html" %}

{% block views-manager-child %}

<h3>Join Group</h3>
<form id="groupSearchForm" action="#">
	<input type="text" name="groupName" />
	<input type="submit" value="Search" />
</form>
<br />

<table class="table table-striped table-bordered table-condensed">
	<tbody id="groupSearchResults">

	</tbody>
</table>


<hr />
<h3>Joined Groups</h3>

<table class="table table-striped table-bordered table-condensed">	
	<thead>
		<tr>
			<td>Name</td>
			<td>Description</td>
			<td>Cretion Date</td>
			<td>Users Count</td>
			<td>Action</td>
		</tr>
	</thead>
	<tbody id="groupsView">

	</tbody>
</table>

<hr />
<h3>Create Group</h3>

<div id="addGroupFormContainer">
	{{createGroupFormData}}
</div>

<hr />
<h3>Owned Groups</h3>
<table class="table table-striped table-bordered table-condensed">
	<thead>
		<tr>
			<td>Name</td>
			<td>Description</td>
			<td>Cretion Date</td>
			<td>Users Count</td>
			<td>Action</td>
		</tr>
	</thead>
	<tbody id="ownedGroups">

	</tbody>
</table>

<table style="display: none;">
	<tbody id="groupTableItemTemplate">
		<tr>
			<td>_groupName_</td>
			<td>_description_</td>
			<td>_cretionDate_</td>
			<td>_usersCount_</td>
			<td><a href="_action_">_actionName_</a></td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
var userName="{{userName}}";

function getTemplatedGroups(groupData, action, actionName)
{
	var compiledData = "";
	$.each( groupData, function( key, val ) {
		var template = $("#groupTableItemTemplate").html();
		var actAction = action.replace("_groupName_", val['name'])
		newHtml = template
			.replace(/_groupName_/g, val['name'])
			.replace("_cretionDate_", val['creationDate'])
			.replace("_description_", val['description'])
			//.replace("_userName_", userName)
			.replace("_action_", actAction)
			.replace("_actionName_", actionName)
			.replace("_usersCount_", val['userCount']);
		compiledData+=newHtml;
	});
	return compiledData;
}

$("#groupSearchForm").submit(function( event ) {
	event.preventDefault();

	var groupName = $("#groupSearchForm").find("input[name='groupName']").val();
	if (groupName=="")
	{
		groupName = "_all";
	}

	$.getJSON( "/data/group-search/"+groupName+"/", function( data ) {
		$("#groupSearchResults").html(getTemplatedGroups(data, "/map/add-user-to-group/"+userName+"/_groupName_/", "Join"));
	});

});

function loadUsersGroups(userName) {
	$.getJSON( "/data/groups-by-user/"+userName+"/", function( data ) {
		$("#groupsView").html(getTemplatedGroups(data, "/map/remove-user-from-group/"+userName+"/_groupName_/", "Leave"));
	});
}

function loadOwnedGroups(userName) {
	$.getJSON( "/data/groups-owned-by-user/"+userName+"/", function( data ) {
		$("#ownedGroups").html(getTemplatedGroups(data, "/map/delete-group/_groupName_/", "Delete"));
	});
}

$( document ).ready(function() {
	loadUsersGroups(userName);
	loadOwnedGroups(userName);
});

createGroupForm.groupCreatedCallback(function(){
	loadUsersGroups(userName);
	loadOwnedGroups(userName);
});

</script>

{% endblock views-manager-child %}

sources/mapler/templates/map/manage-points.html
{% extends "map/views-manager.html" %}
{% load staticfiles %}

{% block views-manager-child %}

<div id="map_canvas" style="width:800px; height:500px"></div>
<div id="point-editing-zone">
	<div id="editingPointHtmlData" style="display: none;">{{editingPointHtmlData}}</div>
	<div id="addingPointHtmlData" style="display: none;">{{addingPointHtmlData}}</div>
</div>
<div id="point-attachments-zone">
	<div id="pointAttachmentsHtmlData" style="display: none;">{{pointAttachmentsHtmlData}}</div>
</div>

<script type="text/javascript"
	src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false">
</script>

<script type="text/javascript">
	var pointsData = [] ;

	var pointEditor = {
		showEditor: function (pointId) {
			var point = null;
			$.each(pointsData, function( index, entry ) {
				if (entry.id == pointId)
					point = entry;
			});

			if (point == null)
				return;

			$( "div#addingPointHtmlData" ).hide();
			$( "div#editingPointHtmlData" ).show();
			$( "div#pointAttachmentsHtmlData" ).show();

			$( "div#point-editing-zone" ).find( "#id_maplerId" ).val(pointId);
			$( "div#point-editing-zone" ).find( "#id_latitude" ).val(point.latitude);
			$( "div#point-editing-zone" ).find( "#id_longitude" ).val(point.longitude);
			$( "div#point-editing-zone" ).find( "#id_description" ).val(point.description);
			$( "div#point-editing-zone" ).find( "a#delete-point-button" ).attr('href', '/map/delete-point/' + point.id +'/');

			$( "div#point-editing-zone" ).find( "#id_group" ).html('<option selected value="'+point.group+'">'+point.group+'</option>');

			pointAttacmentsManager.initialize(pointId, true, '/map/manage-points/');
		},
		showAddingForm: function (latitude, longitude) {
			$( "div#editingPointHtmlData" ).hide();
			$( "div#addingPointHtmlData" ).show();
			$( "div#pointAttachmentsHtmlData" ).hide();

			$.getJSON( "/data/groups-by-user/{{userName}}/", function( data ) {
				if (data.length==0) {
					$( "div#addingPointHtmlData" ).html("<h3>Please join or create a group first.</h3>");
				} else {
					$( "div#point-editing-zone" ).find( "input#id_latitude" ).val(latitude);
					$( "div#point-editing-zone" ).find( "input#id_longitude" ).val(longitude);

					$( "div#addingPointHtmlData" ).find( "#id_group" ).html("");
					$.each(data, function(index, value){
						var option = '';
						if (index == 0){
							option = '<option selected value="'+value.name+'">'+value.name+'</option>';
						} else {
							option = '<option value="'+value.name+'">'+value.name+'</option>';
						}

						$( "div#addingPointHtmlData" ).find( "#id_group" ).append(option);
					});

				}
			});
		}
	}

	function loadPointsData(callback) {
	$.getJSON( "/data/points-by-user/{{userName}}/", function( data ) {
		pointsData = data;
		callback();
	});

	}

	function getPointOnClickCallback(pointId) {
		pointEditor.showEditor(pointId);
	}

	function getMapOnClickCallback(latitude, longitude) {
		pointEditor.showAddingForm(latitude, longitude);
	}

</script>

<script type="text/javascript" src="{% static "map/script/map_common.js" %}"></script>

{% endblock views-manager-child %}

sources/mapler/templates/map/master.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<title>Mapler</title>

	<link rel="stylesheet" href="{% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "map/css/style.css" %}">
    <link rel="stylesheet" href="{% static "map/css/bootply.css" %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script type="text/javascript">
		$.ajaxSetup({
			cache: false
		});
	</script>

</head>
<body>
	<div id="header" class="navbar navbar-default navbar-fixed-top">
	    <div class="navbar-header">

	    	<!-- What the button? -->
	        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
	            <i class="icon-reorder"></i>
	        </button>

	        <a class="navbar-brand" href="/">Mapler</a>
	    </div>
	    <nav class="collapse navbar-collapse">
	        <ul class="nav navbar-nav pull-right">
	            {% include "map/user-auth-block.html" %}
	        </ul>
	    </nav>
	</div>

	<div id="wrapper">
		{% block master-child %}
			Default content here...
		{% endblock master-child %}
	</div>

	<!-- Scripts at the and to make the loading faster -->
	<!-- Bootstrap controls -->
	<script src="{% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}"></script>

</body>
</html>

sources/mapler/templates/map/overwiev.html
{% extends "map/views-manager.html" %}
{% load staticfiles %}

{% block views-manager-child %}

<div id="map_canvas" style="width:800px; height:500px"></div>
<div id="point-editing-zone">
	<div id="previewPointHtmlData" style="display: none;">{{previewPointHtmlData}}</div>
</div>
<div id="point-attachments-zone">
	<div id="pointAttachmentsHtmlData" style="display: none;">{{pointAttachmentsHtmlData}}</div>
</div>

<script type="text/javascript"
	src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false">
</script>

<script type="text/javascript">
	// To be filled on server side
	var pointsData = [] ;

	var pointEditor = {
		showInfo: function (pointId) {
			var point = null;
			$.each(pointsData, function( index, entry ) {
				if (entry.id == pointId)
					point = entry;
			});

			if (point == null)
				return;

			$( "div#previewPointHtmlData" ).show();
			$( "div#pointAttachmentsHtmlData" ).show();

			$( "div#point-editing-zone" ).find( "#id_owner" ).html(point.owner);
			$( "div#point-editing-zone" ).find( "#id_owningGroup" ).html(point.group);
			$( "div#point-editing-zone" ).find( "#id_creationDate" ).html(point.creationDate);
			$( "div#point-editing-zone" ).find( "#id_latitude" ).html(point.latitude);
			$( "div#point-editing-zone" ).find( "#id_longitude" ).html(point.longitude);
			$( "div#point-editing-zone" ).find( "#id_description" ).html(point.description);

			pointAttacmentsManager.initialize(pointId, true, '/map/overview/');
		},
		clear: function() {
			$( "div#previewPointHtmlData" ).hide();
			$( "div#pointAttachmentsHtmlData" ).hide();
		}
	}

	function loadPointsData(callback) {
		$.getJSON("/data/points/", function( data ) {
			pointsData = data;
			callback();
		});

	}

	function getPointOnClickCallback(pointId) {
		pointEditor.showInfo(pointId);
	}

	function getMapOnClickCallback(latitude, longitude) {
		pointEditor.clear();
	}

</script>

<script type="text/javascript" src="{% static "map/script/map_common.js" %}"></script>

{% endblock views-manager-child %}

sources/mapler/templates/map/point-edit.html
<div class="point">
	<h3>
		{% if mode == "edit" %}
			Edit Point
		{% else %}
			Add New Point
		{% endif %}
	</h3>

	{% if mode == "edit" %}
		<a id="delete-point-button" href="/map/delete-point/%point-id%">Delete Point</a><br />
	{% endif %}

	<form action="/map/submit-point/" method="post">{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Submit">
	</form>

</div>

sources/mapler/templates/map/point-view.html
<div class="point">
	<h3>Point Info</h3>
		
	<table style="width:300px">
		<tr>
			<td>Description: </td>
			<td id="id_description"></td>
		</tr>
		<tr>
			<td>Owner: </td>
			<td id="id_owner"></td>
		</tr>
		<tr>
			<td>Group: </td>
			<td id="id_owningGroup"></td>
		</tr>
		<tr>
			<td>Added: </td>
			<td id="id_creationDate"></td>
		</tr>
		<tr>
			<td>Latitude: </td>
			<td id="id_latitude"></td>
		</tr>
		<tr>
			<td>Longitude: </td>
			<td id="id_longitude"></td>
		</tr>
	</table>

</div>

sources/mapler/templates/map/user-auth-block.html
<div id="user-auth-block">

	{% if userName == None %}
		<a class="user-auth-link" href="/users/login/">Log In</a>&nbsp;
		<a class="user-auth-link" href="/users/create/">Sign Up</a>
	{% else %}
		<li class="dropdown">
		    <a href="/#" id="nbAcctDD" class="dropdown-toggle user-auth-link" data-toggle="dropdown"><i class="icon-user"></i>{{userName}}<i class="icon-sort-down"></i></a>
		    <ul class="dropdown-menu pull-right">
		        <li><a href="/users/logout/">Log Out</a></li>
		    </ul>
		</li>
	{% endif %}
</div>

sources/mapler/templates/map/views-manager.html
{% extends "map/master.html" %}

{% block master-child %}

<div id="sidebar-wrapper" class="col-md-1">
	<div id="sidebar">
	    <ul class="nav list-group">
	        <li>
	            <a class="list-group-item" href="/map/overview/"><i class="icon-home icon-1x"></i>Overview</a>
	        </li>
	        <li>
	            <a class="list-group-item" href="/map/manage-points/"><i class="icon-home icon-1x"></i>Manage Points</a>
	        </li>
	        <li>
	            <a class="list-group-item" href="/map/manage-groups/"><i class="icon-home icon-1x"></i>Manage Groups</a>
	        </li>
	    </ul>
	</div>
</div>

<div id="main-wrapper" class="col-md-11 pull-right">
    <div id="main">
		<div class="page-header">
			<h3>{{viewName}}</h3>
		</div>

		{% block views-manager-child %}
			Default content here...
		{% endblock views-manager-child %}

    </div>
</div>

{% endblock master-child %}